version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: helpdeskpro_db
    environment:
      - SA_PASSWORD=SenhaForte123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data:
